### ISSUE TITLE
Example ESPHome config

### ISSUE THREAD

**Issue by XMaarten** [nicostrown/ESPHome-Pentair-Intelliflo#1]
Could you please add an example ESPHome configuration on how to configure this? Do you have this working succesfully already?

**Comment by nicostrown** [comment]
I put an example yaml file from my current config. Currently I only managed to have a periodic pull of running data from the pump... and this is working yes.

I sort of copy/paste from a previous personal pump arduino management and most of the commands are supposed to work, but not tested yet (my pump is winterized now).
